# Generated by Django 5.0.1 on 2024-02-16 01:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_edit_profile_bio_edit_profile_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Edit_Profile',
            new_name='Profile',
        ),
    ]
