# Generated by Django 5.0.1 on 2024-02-16 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profile_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='author',
        ),
    ]
